name: Upload hub data to cloud storage

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Hubverse AWS account number
  AWS_ACCOUNT: 767397675902

permissions:
  contents: read
  # id-token write required for AWS auth
  id-token: write

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get hub cloud config
      # save cloud-related fields from admin config as environment variables
      # (jq json parser is installed on Github-hosted runners)
      run: |
        cloud_enabled=$(cat ./hub-config/admin.json | jq -r '.cloud.enabled') \
          && echo "CLOUD_ENABLED=$cloud_enabled"
        cloud_host=$(cat ./hub-config/admin.json | jq -r '.cloud.host.name') \
          && echo "CLOUD_HOST=$cloud_host"
        cloud_storage_service=$(cat ./hub-config/admin.json | jq -r '.cloud.host.storage_service') \
          && echo "CLOUD_STORAGE_SERVICE=$cloud_storage_service"
        cloud_storage_location=$(cat ./hub-config/admin.json | jq -r '.cloud.host.storage_location') \
          && echo "CLOUD_STORAGE_LOCATION=$cloud_storage_location"
        echo "CLOUD_ENABLED=$cloud_enabled" >> $GITHUB_ENV
        echo "CLOUD_HOST=$cloud_host" >> $GITHUB_ENV
        echo "CLOUD_STORAGE_SERVICE=$cloud_storage_service" >> $GITHUB_ENV
        echo "CLOUD_STORAGE_LOCATION=$cloud_storage_location" >> $GITHUB_ENV

    - name: Configure AWS credentials
      # request credentials to assume the hub's AWS role via OpenID Connect
      if: env.CLOUD_ENABLED == 'true'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/${{ env.CLOUD_STORAGE_LOCATION }}
        aws-region: us-east-1

    - name: Sync files to cloud storage
      # sync specified hub directories to S3
      # (to exclude a directory, remove it from the list of hub_directories below)
      if: env.CLOUD_ENABLED == 'true'
      run: |
        hub_directories=(
          'testy'
          #'auxiliary-data'
          #'hub-config'
          #'model-abstracts'
          #'model-metadata'
          #'model-output'
          #'target-data'
        )
        for DIRECTORY in "${hub_directories[@]}"
        do
          if [ -d "./$DIRECTORY" ]; then aws s3 sync "./$DIRECTORY" "s3://$BUCKET_NAME/$DIRECTORY" --delete; fi
        done
      shell: bash
      env:
        BUCKET_NAME: ${{ env.CLOUD_STORAGE_LOCATION }}
