name: Upload hub data to cloud storage

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    # write permissions required to fetch a token for AWS authorization
    permissions:
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get hub cloud config
      # save cloud-related fields from admin config as environment variables
      # (jq is installed on Github-hosted runners)
      run: |
        cloud_enabled=$(cat ./hub-config/admin.json | jq -r '.cloud.enabled') && echo "CLOUD_ENABLED=$cloud_enabled"
        cloud_host=$(cat ./hub-config/admin.json | jq -r '.cloud.host.name') && echo "CLOUD_HOST=$cloud_host"
        cloud_storage=$(cat ./hub-config/admin.json | jq -r '.cloud.host.storage') && echo "CLOUD_STORAGE=$cloud_storage"
        echo "CLOUD_ENABLED=$cloud_enabled" >> $GITHUB_ENV
        echo "CLOUD_HOST=$cloud_host" >> $GITHUB_ENV
        echo "CLOUD_STORAGE=$cloud_storage" >> $GITHUB_ENV

    - name: Configure AWS credentials
      if: env.CLOUD_ENABLED == 'true'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::767397675902:role/${{ env.CLOUD_STORAGE }}
        aws-region: us-east-1

    - name: Sync files to cloud storage
      if: env.CLOUD_ENABLED == 'true'
      run: |
        aws s3 sync ./hub-config "s3://$CLOUD_STORAGE/hub-config" --delete
        aws s3 sync ./model-metadata "s3://$CLOUD_STORAGE/model-metadata" --delete
        aws s3 sync ./model-output "s3://$CLOUD_STORAGE/raw/model-output" --delete
      env:
        CLOUD_STORAGE: ${{ env.CLOUD_STORAGE }}
